js/editor.js

fixes https://github.com/owncloud/core/issues/11412
The message vanishes after 7 seconds (I just used the default timeout)
cc @jancborchardt @PVince81 @jnfrmarks

vanish notification about unsaved changes after a period of time

---

ajax/savefile.php

Fixes error reported in `occ app:check-code`
Fixes #68

Fix static method call on private class

---

js/editor.js

A YAML file will be downloaded instead of edited when opened from the files app. This pull request will instead try to edit the file.

Add yaml to file actions

---

js/editor.js

fixes #61; replaces #92 
cc @MorrisJobke 
@eephyne please check if you can scroll the editor now

Place editor inside of app-content

---

js/editor.js

cc @felixboehm @LukasReschke @nickvergessen @oparoz 
Backport approval: https://github.com/owncloud/files_texteditor/pull/89#issuecomment-123676131

[stable8.1] Add yaml to file actions

---

css/style.css

This fixes the public link page.
Fixes https://github.com/owncloud/core/issues/19273
Please review @LukasReschke @tomneedham @oparoz

Properly namespace CSS to not break core styles

---

js/editor.js

* disable transpose letters shortcut in Ace
* fixes #118
cc @schiesbn @lukasreschke @tomneedham

Re-enable Ctrl-T shortcut in browser

---

js/editor.js

Close the texteditor when we fail to load the file

---

js/editor.js

Remove duplicate ajax call

---

js/editor.js

Adding icon to edit action in action menu

---

controller/filehandlingcontroller.php
tests/controller/filehandlingcontrollertest.php

backport of https://github.com/owncloud/files_texteditor/pull/123
cc @DeepDiver1975 @LukasReschke @tomneedham

[stable8.1] fix error messages in case a file couldn't be read 

---

js/editor.js

Fixes https://github.com/owncloud/files_texteditor/issues/133
@butonic

Update file size in list when closing editor

---

js/editor.js

- Preserves the title (doesn't prepend * each time)
- Stops the saving message disappearing for the second save
- Leaves the * next to the filename
To test:
- Add a `sleep(2);` to https://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L131
- Create and open a text file
- Add some content
- Wait till autosave starts
- Type some more content
- Observe that the * stays in the filename and document title and that autosave kicks in again
Fixes #121 
@PVince81

Handle editing file whilst saving

---

js/editor.js

See #130.
@karlitschek @PVince81

Backport of #130 to 8.2 - Handle editing whilst saving.

---

css/style.css

Please review @tomneedham @owncloud/designers 
In addition it would be cool to also implement »Close when clicking outside of editor« #132

overlay header as well for better focus

---

js/editor.js

Fixes https://github.com/owncloud/files_texteditor/issues/132
@jancborchardt

Close editor when clicking outside of the container

---

.travis.yml

@LukasReschke @tomneedham 
Needs to be backported to stable8.2, so we can backport https://github.com/owncloud/files_texteditor/pull/153

Remove invalid travis testing

---

.gitignore
controller/filehandlingcontroller.php
js/editor.js
tests/bootstrap.php
tests/controller/filehandlingcontrollertest.php
tests/phpunit.xml

Fix #126 
@schiesbn @tomneedham 
might be worth backporting

Display the error message when one was given

---

css/style.css
js/editor.js

Before: ![](https://i.imgur.com/GVBQyzI.png)
After: ![](https://i.imgur.com/GAYORgk.png)
cc @tomneedham

Dont hide main navigation when showing a preview

---

js/editor.js

@SergioBertolinSG 
Not a major bug, so do we back port? @PVince81

Dont close editor when selecting text, fixes #158

---

js/editor.js

refs https://github.com/owncloud/core/pull/24491#issuecomment-217789787

Remove loading icon when data loaded

---

js/editor.js

added mime type for .htaccess files to be able to edit them online

added mime type for .htaccess files

---

Makefile
appinfo/info.xml

Makefile to create appstore tar.gz package.

Makefile with appstore target

---

js/editor.js

Reverts owncloud/files_texteditor#190

Revert "added mime type for .htaccess files"

---

README.md
appinfo/info.xml

Signed-off-by: Phil Davis <phil@jankaritech.com>

Minor info and readme wording changes

---

.travis.yml
tests/travis/start_coverage_report.sh
tests/travis/start_php_lint_tests.sh
tests/travis/start_php_unit_tests.sh
tests/travis/start_ui_tests.sh
tests/ui/config/behat.yml
tests/ui/features/bootstrap/TextEditorContext.php
tests/ui/features/bootstrap/bootstrap.php
tests/ui/features/lib/TextEditorPage.php
tests/ui/features/textfiles.feature

An initial set of UI tests that:create new text files with the text editor, using various filenames and putting bits of text in the files.
To do:

Text editor UI tests

---

tests/ui/features/bootstrap/TextEditorContext.php

Refactor away local use of ocPath, like what has been done in core.

ocPath refactoring to match core master and stable10

---

tests/ui/features/bootstrap/TextEditorContext.php

This works against the latest refactored code in master, and IMO is a bit cleaner than the version last week.

Auto enable and disable app for UI test runs

---

tests/travis/start_ui_tests.sh

To reflect the change done in core by https://github.com/owncloud/core/pull/29037

Rename core start_ui_tests script

---

appinfo/application.php
controller/filehandlingcontroller.php

My IDE tells me about a couple of unused ``use`` statements.

Remove unused use statement

---

.travis.yml
tests/travis/start_ui_tests.sh
tests/ui/features/bootstrap/TextEditorContext.php

Which is needed because of core https://github.com/owncloud/core/pull/29763 which now uses ``xmllint`` in ``start_ui_tests.sh``

Add libxml2-utils to get xmllint

---

tests/ui/features/bootstrap/TextEditorContext.php

cleanup unused use statements since recent refactoring for core test changes

Remove unused use in TextEditorContext

---

appinfo/application.php
appinfo/routes.php
controller/filehandlingcontroller.php
tests/controller/filehandlingcontrollertest.php

might as well bump these while I am checking that CI here still passes against core.

Welcome 2018 text editor

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/textfiles.feature

Refactor UI tests to remove regular user and group

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/bootstrap.php

and tell behat about FeatureContext that is now needed from core.

Do not load WebUIBasicStructure as it is gone

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/TextEditorContext.php

and remove an unused ``tmpDir``

Use standard ocPath that goes via testing app

---

.travis.yml

Clone the testing app, which is now a separate app.
Issue #248

clone the testing app

---

.travis.yml

Title says it all.
There is a separate issue to move CI to drone.

Add webUI acceptance tests on PHP 7.2

---

tests/acceptance/features/webUITextEditor/createTextFiles.feature
tests/acceptance/features/webUITextEditor/editTextFiles.feature

1) Indent feature files 2 characters
2) Fixup creation of user1
3) See if CI passes

Refactor tests 20181003

---

.gitignore
.php_cs.dist
Makefile
composer.json
composer.lock
vendor-bin/owncloud-codestyle/composer.json

Add make commands for running style check, unit tests and acceptance tests
Fixes #258

Add Make commands for style check and unit tests

---

tests/acceptance/features/lib/TextEditorPage.php

use the new CRUD object to find the "+" button to create a new file
depends on https://github.com/owncloud/core/pull/33510 to be in the QA tarball
fixes #260

use new CRUD page object

---

.drone.yml
appinfo/app.php
appinfo/application.php
appinfo/routes.php
controller/filehandlingcontroller.php
tests/controller/filehandlingcontrollertest.php

Related issue #265
Added oc-coding-standard test in drone and fixed code style

Fix code style and add owncloud coding standard in drone

---

tests/acceptance/features/lib/TextEditorPage.php

Issue #280
See test PR #279 for a demonstration of the scenario running many times and failing, then passing with this commit applied.

Wait more nicely for editor to close

---

Makefile

Part of issue https://github.com/owncloud/QA/issues/609

Remove unneeded composer var in Makefile

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/TextEditorContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/webUIActivityList/activityList.feature

part of https://github.com/owncloud/activity/issues/677

test if actions are loged by the activity app

---

composer.lock
tests/acceptance/features/bootstrap/TextEditorContext.php
tests/unit/controller/filehandlingcontrollerTest.php

1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) Update bamarni/composer-bin-plugin (v1.3.0)  (while we are here)

Php unit 5 to 6

---

tests/acceptance/features/webUIActivityList/activityList.feature
tests/acceptance/features/webUITextEditor/createTextFiles.feature
tests/acceptance/features/webUITextEditor/editTextFiles.feature

Adjust create user test steps

---

.drone.yml

Currently we only run app tests against stable10 to make sure they will be compatible with the future OC core platform release.
This test guarantee that the ```files_texteditor``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611

files-editor app test against latest release tarball

---

.drone.starlark
.drone.yml

Note: in other app repos with webUI acceptance tests, we managed to also run them on Firefox. But they do pass on Firefox for this repo. This PR is just about adding a drone starlark script, so I won't spend time here trying to get UI acceptance tests running on Firefox.

Initial drone starlark config

---

.drone.starlark
.drone.yml
composer.json
composer.lock
phpunit.xml
tests/unit/controller/filehandlingcontrollerTest.php
vendor-bin/behat/composer.json

Similar to https://github.com/owncloud/configreport/pull/121

Adjust tests

---

js/editor.js

Only update file stats in file list if file data is available

---

phpstan.neon
vendor-bin/phpstan/composer.json

Related - owncloud/QA#642
Update phpstan to 0.12

[Tests-Only] Update phpstan to latest version

---

.drone.star
.phan/config.php
appinfo/application.php
vendor-bin/phan/composer.json

Part of https://github.com/owncloud/QA/issues/643

[Tests-Only] Bump phan 2.7 & Run phan in CI

---

.gitignore
vendor-bin/behat/composer.json

Part of https://github.com/owncloud/QA/issues/647

[Tests-Only] Implement PHPunit v8

---

tests/acceptance/config/behat.yml
tests/acceptance/features/webUITextEditor/editTextFiles.feature

Delete and restore hidden text file
https://github.com/owncloud/core/issues/36233
- To add more acceptance test scenarios for files_texteditor

[Tests-Only] Restore hidden text file

---

tests/acceptance/features/webUIActivityList/activityList.feature
tests/acceptance/features/webUITextEditor/createTextFiles.feature
tests/acceptance/features/webUITextEditor/editTextFiles.feature

Similar to what was done in core recently.

Use realistic usernames

---

js/editor.js

This fix will show up a more detailed display name in the files actions menu.
required for PR https://github.com/owncloud/core/pull/38132

Enhance context menu

---

.drone.star
phpstan.neon

It is easy - follow-on from PR #335

[tests-only] Enable phpstan

---

tests/acceptance/features/webUIActivityList/activityList.feature
tests/acceptance/features/webUITextEditor/createTextFiles.feature
tests/acceptance/features/webUITextEditor/editTextFiles.feature

now that there is no default skeleton.

[tests-only] Specify needed files and folders in tests

---

appinfo/app.php
appinfo/application.php
appinfo/routes.php
controller/filehandlingcontroller.php
js/editor.js
phpstan.neon
tests/acceptance/config/behat.yml
tests/acceptance/features/webUITextEditor/editSharedTextFiles.feature
tests/acceptance/features/webUITextEditor/editTextFilesInSharedFolder.feature
tests/unit/ApplicationTest.php
tests/unit/controller/filehandlingcontrollerTest.php

Also improved the loading of the app a bit in the course of this.
fixes https://github.com/owncloud/enterprise/issues/4712

Implement public link support

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

prepare release 2.4.0

---

appinfo/info.xml

fixes https://github.com/owncloud/files_texteditor/issues/361

Add missing namespace in info.xml file

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Release 2.4.1

---

tests/acceptance/features/bootstrap/TextEditorContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/TextEditorPage.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only][full-ci] enforce strict type checking in acceptace tests code

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Merge back Release 2.5.1

---

.drone.star
appinfo/application.php
composer.json
composer.lock
controller/filehandlingcontroller.php
phpstan.neon
tests/unit/controller/filehandlingcontrollerTest.php
vendor-bin/behat/composer.json
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/php_codesniffer/composer.json
vendor-bin/phpstan/composer.json

- update `.drone.star` code from activity app
- update tool dependencies
- update to coding-style 4.1

[tests-only] [full-ci] Update tool dependencies and drone CI code

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

2.5.2 release was made a couple of weeks ago.
Merge into master.

Merge back Release 2.5.2

---

tests/acceptance/features/webUITextEditor/createTextFiles.feature
tests/acceptance/features/webUITextEditor/editTextFiles.feature

Part of: owncloud/QA#825
> Note: This PR was made by an automated script, in case something is not right I'll take care of it manually.

[tests-only] fix the line syntax

---

controller/filehandlingcontroller.php

Fix: https://github.com/owncloud/files_texteditor/issues/411

fix: release locks on not converted files

---

CHANGELOG.md
appinfo/info.xml
controller/filehandlingcontroller.php
sonar-project.properties

Merge back Release 2.6.1
