- ajax/loadfile.php
Return error message in case something goes wrong while reading a file (e.g. because it is encrypted and the user doesn't has the correct key)
cc @PVince81 @nickvergessen  @th3fallen
> improved error handling if something goes wrong

- js/editor.js
The mime type was misspelled. This fixes https://github.com/owncloud/files_texteditor/issues/25
> Update editor.js to fix perl files

- README.md
- css/style.css
- js/editor.js
Allows 3rdparty apps to register previews for certain mimetypes.
Example usage: https://github.com/icewind1991/owncloud-markdown/tree/texteditor-2.0
cc @jancborchardt @tomneedham
> Add api that allows other app to register "previews" by mimetype

- controller/filehandlingcontroller.php
- tests/controller/filehandlingcontrollertest.php
In case of not existant files this could leak informations such as the full path.
Fixes https://github.com/owncloud/security-tracker/issues/180
> Do not show actual error message

- appinfo/app.php
This will only load the scripts and CSS whenever the files app is displayed (and reduce the risk of side-effects on pages where the text editor is not intended to be used, like public links)
@tomneedham @LukasReschke
> Only load scripts when needed

- js/editor.js
Fixes https://github.com/owncloud/files_texteditor/issues/111
@tomneedham it seems you didn't know how to bind functions, check `_.bind()`. It makes it possible to use the context "this" without having to resort every time to accessing the global object like you did.
Is there any way to get the new size of the file ? (note: in the future the refreshing can be done with a single PROPFIND)
> Update file list row after save

- controller/filehandlingcontroller.php
- tests/controller/filehandlingcontrollertest.php
In case of not existant files this could leak informations such as the full path.
Backport of https://github.com/owncloud/files_texteditor/pull/96
> [stable8.1] Do not show actual error message

- controller/filehandlingcontroller.php
- tests/controller/filehandlingcontrollertest.php
if the exception contain a hint what went wrong we display it to the user if not we display a generic error message
fix bug introduced here: https://github.com/owncloud/files_texteditor/pull/96
cc @DeepDiver1975 @LukasReschke @tomneedham
> fix error messages in case a file couldn't be read

- js/editor.js
Register an entry to create a new text file in the file app's "+" menu.
After file creation, automatically open the editor.
Fixes https://github.com/owncloud/files_texteditor/issues/147
@owncloud/designers  @nickvergessen @schiesbn @icewind1991
> Register "New text file" meu entry in "+" menu

- .travis.yml
If someone forks this repo and then enables their fork in Travis and tries to build, then they get a phpunit error like:
```
$ phpunit --configuration phpunit.xml
PHP Fatal error:  Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in /home/travis/build/phil-davis/core/lib/composer/phpunit/phpunit/src/TextUI/TestRunner.php on line 1076
PHP Stack trace:
PHP   1. {main}() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/.phpenv/versions/5.6.5/bin/phpunit:722
PHP   3. PHPUnit_TextUI_Command->run() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:104
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///home/travis/.phpenv/versions/5.6.5/bin/phpunit/phpunit/TextUI/Command.php:1 …
```
> Travis sudo required is being used so specify it

- CHANGELOG.md
hmmm - there does not seem to be a v2.2 tag to diff from in GitHub.
I guess that apps in the past have had different ways of doing branching and tagging.
> Changelog for changes since V2.2 2017-05-09

- .travis.yml
- tests/travis/start_ui_tests.sh
- tests/ui/config/behat.yml
- tests/ui/features/bootstrap/TextEditorContext.php
- tests/ui/features/textfiles.feature
A change to core ``start_ui_tests.sh`` allows the caller to specify the apps to be enabled for the test by using environment variable ``APPS_TO_ENABLE`` 
Make use of that to reduce code duplication.
Also here:
1) change to using ``sudo: false`` on Travis - we do not need ``sudo`` and the Travis VM will start more quickly.
2) Fixup ``ocPath`` so that it points to the correct place where the testing app API lives.
3) Remove the ``SetupHelper::init`` from ``TextEditorContext`` - that is already in core ``FeatureContext`` that is part of the loaded environment for the tests anyway.
4) Add ``insulate`` to the feature file. That gives us a separate SauceLabs video for each scenario, which is easier to review if a scenario fails.
> Use new core ability to specify APPS_TO_ENABLE for UI test

- tests/acceptance/features/bootstrap/TextEditorContext.php
- tests/acceptance/features/bootstrap/bootstrap.php
- tests/acceptance/features/lib/TextEditorPage.php
- tests/acceptance/features/textfiles.feature
The core UI test step text formats have changed. 
- Update the steps here to match.
- Reword text-editor-specific steps to use the same grammar.
- Adjust code format so ``phpcs`` gives no errors.
> Refactor UI test steps to match core changes

- .travis.yml
- tests/acceptance/config/behat.yml
- tests/acceptance/features/webUITextEditor/createTextFiles.feature
- tests/acceptance/features/webUITextEditor/editTextFiles.feature
The core ``start_ui_tests.sh`` script now expects webUI tests to be in suites in folders under the ``features`` folder.
> Put webUI tests into suite called webUITextEditor

- tests/acceptance/features/lib/TextEditorPage.php
as was done in core https://github.com/owncloud/core/pull/32144
See core issue https://github.com/owncloud/core/issues/32143 for details of the cause.
> Catch StaleElementReference from fillField

- .gitignore
- tests/acceptance/config/behat.yml
- tests/travis/start_ui_tests.sh
After core https://github.com/owncloud/core/pull/31348 it is possible to run webUI acceptance tests from the common ``tests/acceptance/run.sh`` script, so do it.
Note: this app is still using Travis/SauceLabs to run the tests, so I have left it with its existing little stub ``tests/travis/start_ui_tests.sh`` script. That stuff can go when ``files_texteditor`` CI is moved to drone.
> Use run.sh for webUI tests

- tests/acceptance/features/lib/TextEditorPage.php
Old forms of the constant names were deprecated by https://github.com/owncloud/core/pull/32781/commits/db4608ace28ed62a00173021416951fb7ac3d994
Use the new forms that have underscores.
> adjust acceptance test time constant names

- Makefile
1) When doing ``make clean-deps`` also delete the ``vendor`` dir
2) Remove the duplicated ``composer_deps`` stuff that was causing:
```
make
Makefile:161: warning: overriding recipe for target 'vendor'
Makefile:66: warning: ignoring old recipe for target 'vendor'
make: Nothing to be done for 'all'.
```
3) The ``all`` makefile target was doing nothing anyway, get rid of it.
4) Add in the "standard" help target
> Delete vendor dir on clean-deps

- .drone.starlark
- .drone.yml
- tests/acceptance/features/bootstrap/bootstrap.php
- vendor-bin/behat/composer.json
It is needed by core `HttpRequestHelper.php` `parseResponseAsXml`
And there is no longer any need to `make install-composer-deps` in the testrunner core folder, because those dependencies are not used by behat any more.
> Add sabre/xml to behat dependencies

- controller/filehandlingcontroller.php
This PR supersedes https://github.com/owncloud/files_texteditor/pull/51, https://github.com/owncloud/files_texteditor/pull/73 and https://github.com/owncloud/files_texteditor/pull/180
All are adding encodings for China and Japan.
Follow the link to read more about [Chinese Character Encoding Standards](https://www.pinyinjoe.com/pinyin/encoding.htm)
This PR gives Chinese and Japanese users a very good probability to use the editor for editing texts in their native language. Without this PR, the text looks scrambled and the editor is useless.
After further research and according to [stackoverflow](https://stackoverflow.com/questions/11782898/what-is-the-preferable-character-encoding-order-for-mb-detect-encoding-in-p),
_There is no true preferred order that gives you the most accurate …
> Adding encodings (GB2312, GBK ,BIG5, SJIS-win and EUC-JP)

- .phan/config.php
- Makefile
Both commands `make test-php-phan` and `make test-php-phpstan` do not work because they look for the directory `lib` which is not available.
> Fix PHP phan and stan commands

- .drone.star
Do not test text-editor+activity app combination against an "old" 10.7.0 core.
> [tests-only] Activity app now requires core 10.7.1

- .drone.star
- phpunit.xml
- sonar-project.properties
- vendor-bin/behat/composer.json
* Skip coverage for PHP 7.3
* Update `phpunit.xml` to match the new structure for PHPUnit 9.5
* Use phpunit 9 in acceptance test dependencies
> [tests-only] Ensure compatibility with PHPUnit v9.5

- phpunit.xml
This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198
> [tests-only][full-ci]Tidy up the phpunit xml file for `files_texteditor` app

- tests/acceptance/features/webUIActivityList/activityList.feature
- tests/acceptance/features/webUITextEditor/createTextFiles.feature
- tests/acceptance/features/webUITextEditor/editTextFiles.feature
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:
> [full-ci] [tests-only] Refactored inter scenarios space

- .drone.star
- Makefile
- controller/filehandlingcontroller.php
It does not seem safe to rely on vendor/firebase/php-jwt from files_external or elsewhere.
Seems we should package and use our own copy.
Fixes #388
> package vendor/firebase/php-jwt

- composer.lock
mainly doing this to double-check that CI is happy after the Symfony5 update in core.
But we may as well have the latest php-jwt.
> [full-ci] Bump firebase/php-jwt to 6.4.0

- .drone.star
- appinfo/info.xml
- composer.json
- composer.lock
requires https://github.com/owncloud/core/pull/40901
> fix: use firebase/php-jwt from core

- controller/filehandlingcontroller.php
In some cases, `\iconv` may return `false` because of wrongly detected encoding. This messes up with the file content. We now set the encoding back to default ISO-8859-15 (after retrieving again the node content) in case of encoding being wrongly detected.
Related issue: https://github.com/owncloud/files_texteditor/issues/405
> Fix for iconv returning false

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
This was released on 11 August 2023:
https://github.com/owncloud/files_texteditor/releases/tag/v2.6.0
> Merge back 2.6.0

- controller/filehandlingcontroller.php
- tests/unit/controller/filehandlingcontrollerTest.php
**Known issue** caused by this PR: only one password-protected link can be accessed at a time.
1. Access to a shared folder that is password-protected. Enter the password and check you can open text files inside.
2. In a different tab, access to a different shared folder that is password-protected. Enter the password and check you can open text files inside
3. Authentication for the first shared folder (step 1) is lost:
* Trying to open a text file causes an error
* You'll need to reload the page and enter the password again. Note that this will cause the same problem in the second tab.
Side note: whether the link has been authenticated or not is stored by core. Right now, this information is stored just for one share. Fixing the issue explained above will require changes in core.
> fix: ensure password has been checked for password-protected shares and have permissions to read the file
